//! Required `.env` variable registry (contract "Required Env Variables").
//! Extracted from `config_schema_registry.rs` to stay under the monolith line cap.

use super::{EnvVarSpec, PROJECTION_BATCH_KEYS};

type RawEnvVar = (
    &'static str,
    bool,
    bool,
    Option<&'static str>,
    &'static str,
    bool,
    &'static str,
    &'static str,
);

// (name, required, secret, default, owner_crate, compose_usage, validation, description)
const RAW_ENV_VARS: &[RawEnvVar] = &[
    (
        "AXON_DATA_DIR",
        false,
        false,
        None,
        "axon-core",
        false,
        "path",
        "Bootstrap data-dir path override.",
    ),
    (
        "QDRANT_URL",
        true,
        false,
        Some("http://127.0.0.1:6333"),
        "axon-vectors",
        true,
        "url",
        "Vector store URL.",
    ),
    (
        "TEI_URL",
        true,
        false,
        None,
        "axon-embedding",
        true,
        "url",
        "Embedding provider URL.",
    ),
    (
        "AXON_CHROME_REMOTE_URL",
        false,
        false,
        None,
        "axon-adapters",
        true,
        "url",
        "Render provider (headless Chrome) URL.",
    ),
    (
        "AXON_ARTIFACT_CANDIDATE_DEPOT_URL",
        false,
        false,
        None,
        "axon-adapters",
        false,
        "url",
        "Optional Depot base URL for committed ArtifactCandidate delivery; requires the matching token.",
    ),
    (
        "AXON_ARTIFACT_CANDIDATE_DEPOT_TOKEN",
        false,
        true,
        None,
        "axon-adapters",
        false,
        "none",
        "Write-scoped Depot bearer token; requires the matching Depot URL.",
    ),
    (
        "SKILLS_SH_OIDC_TOKEN",
        false,
        true,
        None,
        "axon-adapters",
        false,
        "none",
        "Preferred OIDC bearer token for authenticated skills.sh discovery.",
    ),
    (
        "VERCEL_OIDC_TOKEN",
        false,
        true,
        None,
        "axon-adapters",
        false,
        "none",
        "Intentional fallback OIDC bearer token for skills.sh in Vercel environments.",
    ),
    (
        "AXON_HTTP_HOST",
        false,
        false,
        Some("127.0.0.1"),
        "axon-web",
        false,
        "host",
        "Unified server bind host.",
    ),
    (
        "AXON_HTTP_PORT",
        false,
        false,
        None,
        "axon-web",
        false,
        "port",
        "Unified server bind port.",
    ),
    (
        "AXON_PUBLIC_URL",
        false,
        false,
        None,
        "axon-web",
        false,
        "url",
        "OAuth/public URL.",
    ),
    (
        "AXON_HTTP_TOKEN",
        false,
        true,
        None,
        "axon-web",
        false,
        "none",
        "Static bearer auth token.",
    ),
    (
        "AXON_AUTH_MODE",
        false,
        false,
        None,
        "axon-authz",
        false,
        "enum",
        "One of none, bearer, or oauth.",
    ),
    (
        "AXON_GOOGLE_CLIENT_ID",
        false,
        false,
        None,
        "axon-authz",
        false,
        "none",
        "OAuth client id.",
    ),
    (
        "AXON_GOOGLE_CLIENT_SECRET",
        false,
        true,
        None,
        "axon-authz",
        false,
        "none",
        "OAuth client secret.",
    ),
    (
        "GITHUB_TOKEN",
        false,
        true,
        None,
        "axon-adapters",
        false,
        "none",
        "Private/rate-limited GitHub access.",
    ),
    (
        "GITLAB_TOKEN",
        false,
        true,
        None,
        "axon-adapters",
        false,
        "none",
        "Private/rate-limited GitLab access.",
    ),
    (
        "GITEA_TOKEN",
        false,
        true,
        None,
        "axon-adapters",
        false,
        "none",
        "Private/rate-limited Gitea/Forgejo access.",
    ),
    (
        "REDDIT_CLIENT_ID",
        false,
        false,
        None,
        "axon-adapters",
        false,
        "none",
        "Reddit source client id.",
    ),
    (
        "REDDIT_CLIENT_SECRET",
        false,
        true,
        None,
        "axon-adapters",
        false,
        "none",
        "Reddit source client secret.",
    ),
    (
        "TAVILY_API_KEY",
        false,
        true,
        None,
        "axon-adapters",
        false,
        "none",
        "Search fallback API key.",
    ),
    (
        "AXON_SEARXNG_URL",
        false,
        false,
        None,
        "axon-adapters",
        false,
        "url",
        "Self-hosted SearXNG search provider URL.",
    ),
    (
        "AXON_OPENAI_API_KEY",
        false,
        true,
        None,
        "axon-llm",
        false,
        "none",
        "OpenAI-compatible LLM backend API key.",
    ),
    (
        "AXON_OPENAI_BASE_URL",
        false,
        false,
        None,
        "axon-llm",
        false,
        "url",
        "OpenAI-compatible LLM backend base URL.",
    ),
    (
        "AXON_CODEX_HOME",
        false,
        false,
        None,
        "axon-llm",
        false,
        "path",
        "Codex app-server provider home override.",
    ),
    (
        "AXON_CODEX_CONTROL_ENABLED",
        false,
        false,
        Some("false"),
        "axon-web",
        false,
        "bool",
        "Enable the isolated server-host Codex control plane.",
    ),
    (
        "AXON_CODEX_CONTROL_HOME",
        false,
        false,
        None,
        "axon-web",
        false,
        "path",
        "Absolute dedicated CODEX_HOME for the Codex control plane.",
    ),
    (
        "AXON_CODEX_CONTROL_REQUEST_TIMEOUT_SECS",
        false,
        false,
        Some("30"),
        "axon-web",
        false,
        "positive integer",
        "Timeout in seconds for each Codex control-plane request.",
    ),
    (
        "AXON_CODEX_CONTROL_READ_CONCURRENCY",
        false,
        false,
        Some("4"),
        "axon-web",
        false,
        "positive integer",
        "Maximum concurrent Codex control-plane reads.",
    ),
    (
        "AXON_CODEX_CONTROL_ACCOUNT_WRITES",
        false,
        false,
        Some("false"),
        "axon-web",
        false,
        "bool",
        "Allow approved Codex account mutations.",
    ),
    (
        "AXON_CODEX_CONTROL_CONFIG_WRITES",
        false,
        false,
        Some("false"),
        "axon-web",
        false,
        "bool",
        "Allow approved Codex configuration mutations.",
    ),
    (
        "AXON_CODEX_CONTROL_MCP_WRITES",
        false,
        false,
        Some("false"),
        "axon-web",
        false,
        "bool",
        "Allow approved Codex MCP server mutations.",
    ),
    (
        "AXON_CODEX_CONTROL_PLUGIN_WRITES",
        false,
        false,
        Some("false"),
        "axon-web",
        false,
        "bool",
        "Allow approved Codex plugin and marketplace mutations.",
    ),
    (
        "AXON_CODEX_CONTROL_SKILL_WRITES",
        false,
        false,
        Some("false"),
        "axon-web",
        false,
        "bool",
        "Allow approved Codex skill mutations.",
    ),
];

pub fn env_var_registry() -> Vec<EnvVarSpec> {
    let mut vars: Vec<_> = RAW_ENV_VARS
        .iter()
        .map(
            |&(
                name,
                required,
                secret,
                default,
                owner_crate,
                compose_usage,
                validation,
                description,
            )| {
                EnvVarSpec {
                    name,
                    required,
                    secret,
                    default,
                    owner_crate,
                    compose_usage,
                    validation,
                    example_allowed: !secret,
                    description,
                }
            },
        )
        .collect();
    vars.extend(
        PROJECTION_BATCH_KEYS
            .iter()
            .map(|&(_, default, name, description)| EnvVarSpec {
                name,
                required: false,
                secret: false,
                default: Some(default),
                owner_crate: "axon-core",
                compose_usage: false,
                validation: "positive integer",
                example_allowed: true,
                description,
            }),
    );
    vars
}
