pub const PROJECTION_BATCH_KEYS: &[(&str, &str, &str, &str)] = &[
    (
        "max_inputs",
        "32",
        "AXON_PROJECTION_BATCH_MAX_INPUTS",
        "Maximum decoded inputs per request.",
    ),
    (
        "max_request_bytes",
        "1048576",
        "AXON_PROJECTION_BATCH_MAX_REQUEST_BYTES",
        "Maximum encoded request body bytes.",
    ),
    (
        "max_input_bytes",
        "16384",
        "AXON_PROJECTION_BATCH_MAX_INPUT_BYTES",
        "Maximum decoded bytes for one source input.",
    ),
    (
        "max_query_bytes",
        "16384",
        "AXON_PROJECTION_BATCH_MAX_QUERY_BYTES",
        "Maximum decoded bytes for one query.",
    ),
    (
        "max_idempotency_key_bytes",
        "256",
        "AXON_PROJECTION_BATCH_MAX_IDEMPOTENCY_KEY_BYTES",
        "Maximum idempotency key bytes.",
    ),
    (
        "max_aggregate_input_bytes",
        "262144",
        "AXON_PROJECTION_BATCH_MAX_AGGREGATE_INPUT_BYTES",
        "Maximum aggregate decoded input bytes.",
    ),
    (
        "max_response_bytes",
        "8388608",
        "AXON_PROJECTION_BATCH_MAX_RESPONSE_BYTES",
        "Maximum serialized response bytes.",
    ),
    (
        "max_pages",
        "1000",
        "AXON_PROJECTION_BATCH_MAX_PAGES",
        "Maximum pages created by one request.",
    ),
    (
        "max_manifest_items",
        "10000",
        "AXON_PROJECTION_BATCH_MAX_MANIFEST_ITEMS",
        "Maximum source manifest items.",
    ),
    (
        "max_fetched_bytes_per_item",
        "16777216",
        "AXON_PROJECTION_BATCH_MAX_FETCHED_BYTES_PER_ITEM",
        "Maximum fetched bytes per item.",
    ),
    (
        "max_decompressed_bytes_per_item",
        "33554432",
        "AXON_PROJECTION_BATCH_MAX_DECOMPRESSED_BYTES_PER_ITEM",
        "Maximum decompressed bytes per item.",
    ),
    (
        "max_prepared_bytes",
        "67108864",
        "AXON_PROJECTION_BATCH_MAX_PREPARED_BYTES",
        "Maximum prepared document bytes.",
    ),
    (
        "max_documents",
        "10000",
        "AXON_PROJECTION_BATCH_MAX_DOCUMENTS",
        "Maximum prepared documents.",
    ),
    (
        "max_chunks",
        "100000",
        "AXON_PROJECTION_BATCH_MAX_CHUNKS",
        "Maximum prepared chunks.",
    ),
    (
        "max_vector_points",
        "100000",
        "AXON_PROJECTION_BATCH_MAX_VECTOR_POINTS",
        "Maximum vector points.",
    ),
    (
        "max_elapsed_secs",
        "900",
        "AXON_PROJECTION_BATCH_MAX_ELAPSED_SECS",
        "Maximum elapsed request seconds.",
    ),
    (
        "max_query_window",
        "1000",
        "AXON_PROJECTION_BATCH_MAX_QUERY_WINDOW",
        "Maximum query offset plus limit.",
    ),
    (
        "global_max_in_flight_requests",
        "64",
        "AXON_PROJECTION_BATCH_GLOBAL_MAX_IN_FLIGHT_REQUESTS",
        "Global projection request admission ceiling.",
    ),
    (
        "caller_max_in_flight_requests",
        "8",
        "AXON_PROJECTION_BATCH_CALLER_MAX_IN_FLIGHT_REQUESTS",
        "Per-caller projection request admission ceiling.",
    ),
    (
        "caller_rate_limit_per_minute",
        "120",
        "AXON_PROJECTION_BATCH_CALLER_RATE_LIMIT_PER_MINUTE",
        "Per-caller projection request rate ceiling.",
    ),
];
