export type CortexPaletteAction = {
  id: string;
  label: string;
  description: string;
  category: string;
  cost: "cheap" | "moderate" | "expensive" | "write";
  admin?: boolean;
};

const action = (
  id: string,
  label: string,
  description: string,
  category: string,
  cost: CortexPaletteAction["cost"],
  admin = false,
): CortexPaletteAction => ({ id, label, description, category, cost, admin });

export const CORTEX_PALETTE_ACTIONS: CortexPaletteAction[] = [
  action("search", "Search logs", "Full-text search over syslog messages", "Logs", "cheap"),
  action(
    "filter",
    "Filter logs",
    "Filter indexed fields without full-text search",
    "Logs",
    "cheap",
  ),
  action("tail", "Tail logs", "Show the most recent log entries", "Logs", "cheap"),
  action("errors", "Recent errors", "List recent error-level log entries", "Logs", "cheap"),
  action("context", "Log context", "Show entries around a log pivot", "Logs", "cheap"),
  action("get", "Get log entry", "Fetch one log entry by ID", "Logs", "cheap"),
  action("timeline", "Log timeline", "Chart log volume in time buckets", "Logs", "cheap"),
  action("patterns", "Message patterns", "Find recurring message patterns", "Logs", "expensive"),
  action("apps", "List applications", "Enumerate known application names", "Logs", "cheap"),
  action("source_ips", "List source IPs", "Enumerate unique source addresses", "Logs", "cheap"),

  action("hosts", "List hosts", "Enumerate known source hostnames", "Fleet", "cheap"),
  action("map", "Map homelab", "Map inventory and answer topology questions", "Fleet", "moderate"),
  action(
    "host_state",
    "Host state",
    "Show the latest heartbeat state for a host",
    "Fleet",
    "moderate",
  ),
  action(
    "fleet_state",
    "Fleet state",
    "Show fleet heartbeat and pressure flags",
    "Fleet",
    "expensive",
  ),
  action(
    "silent_hosts",
    "Silent hosts",
    "Find hosts that have stopped reporting",
    "Fleet",
    "moderate",
  ),
  action("clock_skew", "Clock skew", "Detect time drift between hosts", "Fleet", "expensive"),
  action(
    "compose_status",
    "Compose status",
    "Inspect the Cortex Compose stack",
    "Fleet",
    "moderate",
  ),
  action(
    "compose_doctor",
    "Compose doctor",
    "Diagnose Compose ownership and readiness",
    "Fleet",
    "expensive",
  ),

  action(
    "correlate",
    "Correlate events",
    "Correlate events around a time or AI-session anchor",
    "Analysis",
    "moderate",
  ),
  action(
    "correlate_state",
    "Correlate state",
    "Correlate logs with heartbeat summaries",
    "Analysis",
    "expensive",
  ),
  action(
    "topic_correlate",
    "Correlate topic",
    "Resolve a topic and build a unified timeline",
    "Analysis",
    "moderate",
  ),
  action("stats", "Log statistics", "Aggregate log statistics", "Analysis", "expensive"),
  action(
    "ingest_rate",
    "Ingest rate",
    "Show the current log ingestion rate",
    "Analysis",
    "expensive",
  ),
  action(
    "anomalies",
    "Volume anomalies",
    "Detect unusual changes in log volume",
    "Analysis",
    "expensive",
  ),
  action(
    "compare",
    "Compare windows",
    "Compare patterns between two time windows",
    "Analysis",
    "expensive",
  ),
  action(
    "graph",
    "Investigate graph",
    "Resolve entities, neighborhoods, and evidence",
    "Analysis",
    "expensive",
  ),
  action("status", "Cortex status", "Show server health and ingestion status", "Analysis", "cheap"),

  action(
    "unaddressed_errors",
    "Unaddressed errors",
    "List error signatures awaiting acknowledgement",
    "Incidents",
    "moderate",
  ),
  action(
    "notifications_recent",
    "Recent notifications",
    "Show recent notification firings",
    "Incidents",
    "cheap",
  ),
  action(
    "similar_incidents",
    "Similar incidents",
    "Find related historical incidents",
    "Incidents",
    "moderate",
  ),
  action(
    "incident_context",
    "Incident context",
    "Build full context for an incident window",
    "Incidents",
    "moderate",
  ),

  action(
    "sessions",
    "List AI sessions",
    "List indexed AI transcript sessions",
    "AI sessions",
    "cheap",
  ),
  action(
    "search_sessions",
    "Search AI sessions",
    "Full-text search over AI transcripts",
    "AI sessions",
    "cheap",
  ),
  action("usage_blocks", "Session usage", "Summarize AI usage by project", "AI sessions", "cheap"),
  action(
    "project_context",
    "Project context",
    "Build project context from AI transcripts",
    "AI sessions",
    "expensive",
  ),
  action(
    "list_ai_tools",
    "List AI tools",
    "List AI tools observed in transcripts",
    "AI sessions",
    "cheap",
  ),
  action(
    "list_ai_projects",
    "List AI projects",
    "List projects with transcript activity",
    "AI sessions",
    "cheap",
  ),
  action(
    "ai_correlate",
    "Correlate AI activity",
    "Correlate transcript events with syslog",
    "AI sessions",
    "expensive",
  ),
  action(
    "abuse",
    "Detect resource abuse",
    "Find resource-abuse patterns in AI sessions",
    "AI sessions",
    "moderate",
  ),
  action(
    "abuse_incidents",
    "AI abuse incidents",
    "List detected resource-abuse incidents",
    "AI sessions",
    "moderate",
  ),
  action(
    "abuse_investigate",
    "Investigate AI abuse",
    "Deep-dive into an abuse incident",
    "AI sessions",
    "expensive",
  ),

  action(
    "skill_events",
    "Skill events",
    "List extracted AI skill invocations",
    "Agent activity",
    "cheap",
  ),
  action(
    "skill_incidents",
    "Skill incidents",
    "Find negative signals after skill use",
    "Agent activity",
    "moderate",
  ),
  action(
    "skill_investigate",
    "Investigate skill",
    "Deep-dive into a skill-usage incident",
    "Agent activity",
    "expensive",
  ),
  action("mcp_events", "MCP events", "List extracted MCP tool calls", "Agent activity", "cheap"),
  action(
    "mcp_incidents",
    "MCP incidents",
    "Find negative signals after MCP calls",
    "Agent activity",
    "moderate",
  ),
  action(
    "mcp_investigate",
    "Investigate MCP",
    "Deep-dive into an MCP usage incident",
    "Agent activity",
    "expensive",
  ),
  action(
    "hook_events",
    "Hook events",
    "List runtime and configuration hook evidence",
    "Agent activity",
    "cheap",
  ),
  action(
    "hook_incidents",
    "Hook incidents",
    "Find hook failures, timeouts, and friction",
    "Agent activity",
    "moderate",
  ),
  action(
    "hook_investigate",
    "Investigate hook",
    "Deep-dive into a hook incident",
    "Agent activity",
    "expensive",
  ),

  action(
    "artifact_evidence",
    "Artifact evidence",
    "Query bounded artifact ecosystem evidence",
    "Artifacts",
    "cheap",
  ),
  action(
    "artifact_evidence_record",
    "Record artifact evidence",
    "Append source-attributed artifact evidence",
    "Artifacts",
    "write",
    true,
  ),

  action(
    "ack_error",
    "Acknowledge error",
    "Acknowledge an error signature",
    "Admin",
    "write",
    true,
  ),
  action(
    "unack_error",
    "Unacknowledge error",
    "Revoke an error acknowledgement",
    "Admin",
    "write",
    true,
  ),
  action(
    "file_tails",
    "Manage file tails",
    "Manage Cortex-owned file-tail sources",
    "Admin",
    "write",
    true,
  ),
  action(
    "notifications_test",
    "Test notification",
    "Send a test notification through Apprise",
    "Admin",
    "write",
    true,
  ),
  action(
    "llm_invocations",
    "LLM invocation audit",
    "Review invocation and circuit-breaker records",
    "Admin",
    "cheap",
    true,
  ),
  action("help", "Cortex help", "List actions and their parameters", "Admin", "cheap"),
];

export const CORTEX_CATEGORIES = [
  "Logs",
  "Fleet",
  "Analysis",
  "Incidents",
  "AI sessions",
  "Agent activity",
  "Artifacts",
  "Admin",
] as const;
