use super::mcp_action_registry::{
    LIVE_ACTIONS, SubactionKind, deferred_actions, typed_subaction_variants,
};
use crate::schemas::source_input::SourceInput;

pub(super) fn mcp_markdown(inputs: &[SourceInput]) -> String {
    let mut out =
        String::from("<!-- generated by cargo xtask schemas mcp; do not edit directly -->\n\n");
    out.push_str("# MCP Tool Schema Reference\n\n");
    out.push_str("Generated by `cargo xtask schemas mcp`.\n\n");
    out.push_str("Axon supports legacy, atomic and both tool projections, selected by --mcp-tool-projection or AXON_MCP_TOOL_PROJECTION. Legacy remains the default. The canonical runtime registry owns action metadata, real DTO schemas and leaf-operation discovery; xtask imports that registry rather than mirroring it. The dedicated axon_status_dashboard tool is retained in every mode.\n\n");

    out.push_str("## Actions\n\n");
    out.push_str("| Action | Scope | Mutates | Async | Request DTO | Grouped | Description |\n");
    out.push_str("|---|---|---|---|---|---|---|\n");
    for spec in LIVE_ACTIONS.iter() {
        let grouped = !matches!(spec.subaction, SubactionKind::None);
        out.push_str(&format!(
            "| `{}` | {} | {} | {} | `{}` | {} | {} |\n",
            spec.name,
            spec.scope,
            spec.mutates,
            spec.async_job,
            spec.request_dto,
            grouped,
            spec.description
        ));
    }

    out.push_str("\n## Subactions\n\n");
    out.push_str("| Action | Subactions |\n|---|---|\n");
    for spec in LIVE_ACTIONS.iter() {
        let values: Vec<String> = match spec.subaction {
            SubactionKind::None => continue,
            SubactionKind::TypedEnum => typed_subaction_variants(spec.name),
        };
        out.push_str(&format!(
            "| `{}` | `{}` |\n",
            spec.name,
            values.join("`, `")
        ));
    }

    out.push_str(&operation_markdown());

    out.push_str("\n## Deferred Actions\n\n");
    out.push_str(
        "Contract actions (`docs/pipeline-unification/schemas/mcp-tool-schema.md`'s target \
         `Action` enum) absent from the live dispatcher. No request schema is fabricated for \
         these — see `x-axon.deferred_actions` in the generated JSON schema.\n\n",
    );
    out.push_str("| Action | Reason |\n|---|---|\n");
    for entry in deferred_actions() {
        out.push_str(&format!(
            "| `{}` | {} |\n",
            entry["action"].as_str().unwrap_or_default(),
            entry["reason"].as_str().unwrap_or_default()
        ));
    }

    out.push_str("\n## Response Envelope\n\n");
    out.push_str(
        "Every response uses `AxonToolResponse` (see `$defs.AxonToolResponse` in the generated \
         JSON schema) — `ok`, `action`, `subaction`, `request_id`, `contract_version`, `data`, \
         `warnings`, and optional `job`/`watch`/`artifacts`/`pagination`/`trace`.\n\n",
    );

    out.push_str("## Source Inputs\n\n| Path | SHA-256 |\n|---|---|\n");
    for input in inputs {
        out.push_str(&format!("| `{}` | `{}` |\n", input.path, input.checksum));
    }

    out.push_str(
        "\n## Drift Checks\n\nRun `cargo xtask schemas mcp --check`. Registry parity \
                  against the real dispatcher is enforced separately by \
                  `xtask/src/schemas/mcp_action_registry_tests.rs` \
                  (`cargo test -p xtask`).\n",
    );
    out
}

fn operation_markdown() -> String {
    let mut out = String::from(
        "\n## Canonical leaf tools\n\nAtomic calls omit action and subaction: the tool name fixes both. Safety hints do not grant permissions. Search and research require explicit write elevation; extract_start alone supports optional MCP task admission. The generated JSON exports each focused schema and all reachable definitions.\n\n| Tool | Action | Subaction | Scope | Read-only | Destructive | Tasks |\n|---|---|---|---|---|---|---|\n",
    );
    for op in axon_mcp::server::operation_registry() {
        out.push_str(&format!(
            "| `{}` | {} | {} | {} | {} | {} | {} |\n",
            op.name,
            op.action,
            op.subaction.as_deref().unwrap_or("—"),
            op.required_scope.unwrap_or("none"),
            op.read_only,
            op.destructive,
            if op.supports_tasks {
                "optional"
            } else {
                "forbidden"
            }
        ));
    }
    out
}
