pub const FORBIDDEN_FIELD_FRAGMENTS: &[&str] = &[
    "raw_auth",
    "auth_header",
    "authorization",
    "cookie",
    "api_key",
    "apikey",
    "secret",
    "raw_env",
    "env_value",
    "absolute_home",
    "home_path",
    "raw_html",
    "html_blob",
    "adapter_response",
    "response_blob",
];

pub const SECRET_LIKE_FIELD_FRAGMENTS: &[&str] = &[
    "secret",
    "credential",
    "password",
    "passwd",
    "api_key",
    "apikey",
    "access_token",
    "refresh_token",
    "id_token",
    "private_key",
    "client_secret",
];

pub const FORBIDDEN_VALUE_FRAGMENTS: &[&str] = &[
    "authorization:",
    "proxy-authorization:",
    "bearer ",
    "cookie:",
    "set-cookie:",
    "api_key=",
    "apikey=",
    "api-key:",
    "x-api-key:",
    "access_token=",
    "refresh_token=",
    "secret_key=",
    "token=",
];

pub const BARE_SECRET_TOKEN_PREFIXES: &[&str] = &[
    "AIza",
    "ya29.",
    "atk_",
    "sk-proj-",
    "github_pat_",
    "sk-",
    "sk_",
    "ghp_",
    "gho_",
    "ghu_",
    "ghs_",
    "ghr_",
    "xoxb-",
    "xoxp-",
    "glpat-",
    "tvly-",
    "rk_test_",
    "rk_live_",
];
