//! Family-presence inventory from canonical generated CLI, MCP and REST JSON.
//! This is not semantic equivalence between differently named operations.
use anyhow::{Context, Result, bail};
use serde_json::Value;
use std::collections::BTreeSet;
use std::path::Path;

const OUTPUT: &str = "docs/reference/api-parity.md";

fn read(root: &Path, path: &str, pointer: &str) -> Result<Vec<Value>> {
    let source = std::fs::read_to_string(root.join(path))
        .with_context(|| format!("read {path}; run cargo xtask generated-contracts refresh"))?;
    let value: Value = serde_json::from_str(&source).with_context(|| format!("parse {path}"))?;
    let values = value
        .pointer(pointer)
        .and_then(Value::as_array)
        .filter(|values| !values.is_empty())
        .with_context(|| format!("{path}: missing nonempty {pointer} registry"))?;
    Ok(values.clone())
}

fn normalized(value: &str) -> String {
    value.replace('-', "_")
}

fn surface_names(root: &Path) -> Result<[BTreeSet<String>; 3]> {
    let mut cli = BTreeSet::new();
    for command in read(root, "docs/reference/cli/commands.json", "/commands")? {
        let name = command
            .pointer("/path/0")
            .and_then(Value::as_str)
            .context("CLI registry entry has no command path")?;
        cli.insert(normalized(name));
    }
    let mut mcp = BTreeSet::new();
    for operation in read(
        root,
        "docs/reference/mcp/tool-schema.json",
        "/x-axon/operations",
    )? {
        let name = operation
            .get("action")
            .and_then(Value::as_str)
            .context("MCP registry entry has no action")?;
        mcp.insert(normalized(name));
    }
    let mut rest = BTreeSet::new();
    for route in read(root, "docs/reference/rest/openapi.json", "/routes")? {
        let path = route
            .get("path")
            .and_then(Value::as_str)
            .context("REST registry entry has no path")?;
        if let Some(name) = path.strip_prefix("/v1/").and_then(|s| s.split('/').next()) {
            if !name.is_empty() {
                rest.insert(normalized(name));
            }
        }
    }
    Ok([cli, mcp, rest])
}

fn render(root: &Path) -> Result<String> {
    let [cli, mcp, rest] = surface_names(root)?;
    let all: BTreeSet<_> = cli.iter().chain(&mcp).chain(&rest).cloned().collect();
    let mut output = String::from(
        "# API Parity Matrix\n\n\
         <!-- GENERATED by cargo xtask gen-api-parity; do not edit by hand. -->\n\n\
         This is a **family-name presence inventory**, not proof that requests, results, \
         authorization, or every suboperation are interchangeable. Names come from the \
         canonical [CLI registry](cli/commands.json), [MCP operation catalog](mcp/tool-schema.json), \
         and [REST route registry](rest/openapi.json). Hyphens normalize to underscores; \
         singular/plural and source/list distinctions are intentionally not guessed.\n\n",
    );
    output.push_str(&format!(
        "{} family identifiers: {} CLI roots, {} MCP actions, {} REST /v1 segments.\n\n\
         | Operation | CLI | MCP | REST |\n|---|:--:|:--:|:--:|\n",
        all.len(),
        cli.len(),
        mcp.len(),
        rest.len()
    ));
    let mark = |present| if present { "yes" } else { "no" };
    for name in all {
        output.push_str(&format!(
            "| {} | {} | {} | {} |\n",
            name,
            mark(cli.contains(&name)),
            mark(mcp.contains(&name)),
            mark(rest.contains(&name))
        ));
    }
    output.push_str(
        "\nSee the [action navigation](actions/README.md) for explicit transport entrypoints \
         and [crate ownership](../architecture/crate-ownership.md) for shared behavior. \
         The action renderer consumes JSON directly; this table is not its input. \
         MCP includes system/watch operations from the full operation registry, not \
         only primary request-enum variants. Dashboard/resources/tasks remain separate surfaces.\n\n\
         Refresh schemas first with cargo xtask generated-contracts refresh; the matching \
         check command verifies this snapshot and all dependent renderers.\n",
    );
    Ok(output)
}

pub fn write(root: &Path) -> Result<()> {
    let content = render(root)?;
    std::fs::write(root.join(OUTPUT), content).with_context(|| format!("write {OUTPUT}"))?;
    println!("Wrote {OUTPUT}.");
    Ok(())
}

pub fn check(root: &Path) -> Result<()> {
    let expected = render(root)?;
    let actual = std::fs::read_to_string(root.join(OUTPUT)).unwrap_or_default();
    if expected != actual {
        bail!("{OUTPUT} differs; run cargo xtask generated-contracts refresh");
    }
    println!("OK: {OUTPUT} is in sync.");
    Ok(())
}

#[cfg(test)]
#[path = "api_parity_tests.rs"]
mod tests;
