#!/usr/bin/env python3
"""Read-only Axon documentation inventory and expanded local-link audit."""
from __future__ import annotations
import argparse
from collections import Counter
import hashlib
import html
import json
from pathlib import Path
import re
import subprocess
import unicodedata
from urllib.parse import unquote, urlsplit

HISTORY = {'archive', 'sessions', 'reports', 'plans', 'superpowers', 'investigations', 'perf'}

def visible_lines(text):
    fence = None
    frontmatter = text.startswith('---\n')
    for number, line in enumerate(text.splitlines(), 1):
        if frontmatter:
            if number > 1 and line.strip() == '---':
                frontmatter = False
            yield number, ''
            continue
        match = re.match(r'^\s{0,3}(`{3,}|~{3,})', line)
        if match:
            mark = match[1]
            if fence is None:
                fence = mark
            elif mark[0] == fence[0] and len(mark) >= len(fence):
                fence = None
            yield number, ''
        else:
            yield number, '' if fence else line

def slug(text):
    text = re.sub(r'!?(\[([^]]+)\])\([^)]*\)', r'\2', text)
    text = html.unescape(re.sub(r'<[^>]*>', '', text)).lower()
    text = text.replace('`', '').replace('*', '')
    text = ''.join(c for c in text if c in ' -_' or unicodedata.category(c)[0] in 'LNM')
    return text.replace(' ', '-')

def anchors(text):
    used = set()
    previous = ''
    for _, line in visible_lines(text):
        for anchor in re.findall(r'<[^>]+(?:id|name)=[\"\']([^\"\']+)[\"\']', line):
            used.add(anchor)
        heading = re.match(r'^ {0,3}#{1,6}\s+(.+?)\s*#*$', line)
        title = heading[1] if heading else previous if re.match(r'^ {0,3}(?:=+|-+)\s*$', line) and previous else None
        if title is not None:
            base = slug(title)
            candidate, n = base, 0
            while candidate in used:
                n += 1
                candidate = f'{base}-{n}'
            used.add(candidate)
        previous = line.strip()
    return used

def destination(raw):
    raw = raw.strip()
    if raw.startswith('<') and '>' in raw:
        return raw[1:raw.index('>')]
    return raw.split()[0] if raw else ''

def link_targets(text):
    lines = list(visible_lines(text))
    refs = {}
    normalize = lambda label: ' '.join(label.lower().split())
    for _, line in lines:
        m = re.match(r'^ {0,3}\[([^]\n]+)\]:\s*(.+)$', line)
        if m and not m[1].startswith('^'):
            refs[normalize(m[1])] = destination(m[2])
    for number, line in lines:
        if re.match(r'^ {0,3}\[[^]]+\]:', line):
            continue
        line = re.sub(r'(`+).*?\1', '', line)
        consumed = []
        for match in re.finditer(r'!?\[[^]\n]*\]\(', line):
            start, i, depth = match.end(), match.end(), 1
            while i < len(line) and depth:
                if line[i] == '\\':
                    i += 2
                    continue
                if line[i] == '(':
                    depth += 1
                elif line[i] == ')':
                    depth -= 1
                i += 1
            if depth == 0:
                consumed.append((match.start(), i))
                yield number, destination(line[start:i-1])
        for match in re.finditer(r'!?\[([^]\n]+)\](?:\[([^]\n]*)\])?', line):
            if any(a <= match.start() < b for a, b in consumed):
                continue
            label = normalize(match[2] or match[1])
            if label in refs:
                yield number, refs[label]

def category(path, text, symlink):
    bits = path.split('/')
    if symlink:
        return 'alias'
    if len(bits) > 1 and bits[1] in HISTORY:
        return 'historical'
    if path.startswith(('docs/pipeline-unification/delivery/', 'docs/pipeline-unification/plans/', 'docs/architecture/specs/')):
        return 'design-history'
    if path.endswith(('.json', '.jsonl', '.toml')):
        return 'structured-reference'
    if re.search(r'generated|do not edit', text[:1200], re.I) and ('cargo xtask' in text[:1500] or 'Generated by' in text[:1500] or '<!-- BEGIN GENERATED' in text[:1500]):
        return 'generated-or-mixed'
    return 'current-prose'

def audit(root):
    root = root.resolve()
    tracked = subprocess.check_output(['git', '-C', str(root), 'ls-files', '-z', 'docs'], text=True).split('\0')
    files, findings, code_paths, anchor_cache = [], [], [], {}
    for name in sorted(filter(None, tracked)):
        path = root / name
        if not path.exists():
            findings.append({'path': name, 'kind': 'missing_tracked_file'})
            continue
        raw = path.read_bytes()
        text = raw.decode('utf-8')
        kind = category(name, text, path.is_symlink())
        item = {'path': name, 'category': kind, 'bytes': len(raw), 'lines': len(text.splitlines()), 'sha256': hashlib.sha256(raw).hexdigest(), 'links_checked': 0}
        files.append(item)
        if path.suffix in ('.json', '.jsonl'):
            try:
                if path.suffix == '.json':
                    json.loads(text)
                else:
                    for line in text.splitlines():
                        if line.strip():
                            json.loads(line)
            except (json.JSONDecodeError, ValueError) as error:
                findings.append({'path': name, 'kind': 'invalid_json', 'cause': str(error)})
        if path.suffix != '.md' or kind in ('alias', 'historical', 'design-history'):
            continue
        for number, target in link_targets(text):
            if not target or re.match(r'^[a-zA-Z][a-zA-Z0-9+.-]*:', target) or target.startswith('//'):
                continue
            url = urlsplit(target)
            relative = unquote(url.path)
            item['links_checked'] += 1
            candidate = (root / relative.lstrip('/') if relative.startswith('/') else path.parent / relative).resolve() if relative else path.resolve()
            if not candidate.exists():
                findings.append({'path': name, 'line': number, 'target': target, 'kind': 'missing_link_target'})
                continue
            if url.fragment and candidate.suffix.lower() == '.md' and candidate.is_relative_to(root):
                if candidate not in anchor_cache:
                    anchor_cache[candidate] = anchors(candidate.read_text())
                if unquote(url.fragment).removeprefix('user-content-') not in anchor_cache[candidate]:
                    findings.append({'path': name, 'line': number, 'target': target, 'kind': 'missing_anchor'})
        for number, line in visible_lines(text):
            for match in re.finditer(r'`((?:crates|apps|scripts|deploy|xtask|contracts|plugins|docs)/[^`\s]+)`', line):
                target = re.split(r'(?:::\w|:\d|#)', match[1])[0].rstrip('.,;')
                if any(c in target for c in '*{}<>|') or not Path(target).suffix or target.endswith('/'):
                    continue
                if not (root / target).exists() and not (path.parent / target).exists():
                    code_paths.append({'path': name, 'line': number, 'target': target})
    return {'root_commit': subprocess.check_output(['git', '-C', str(root), 'rev-parse', 'HEAD'], text=True).strip(), 'summary': {'files': len(files), 'categories': dict(Counter(x['category'] for x in files)), 'links_checked': sum(x['links_checked'] for x in files), 'findings': len(findings), 'unresolved_code_paths': len(code_paths)}, 'findings': findings, 'code_paths': code_paths, 'files': files}

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('root', type=Path, nargs='?', default=Path(__file__).resolve().parents[1])
    parser.add_argument('--report', type=Path, help='Write an optional inventory; otherwise check without writes')
    parser.add_argument('--check', action='store_true', help='Fail on broken current links or invalid structured documents')
    args = parser.parse_args()
    try:
        report = audit(args.root.resolve())
        if args.report:
            args.report.write_text(json.dumps(report, indent=2) + '\n')
    except (OSError, UnicodeError, subprocess.CalledProcessError) as error:
        parser.exit(2, f'docs audit: unable to inspect {args.root}: {error}. Verify the checkout and file permissions, then retry. No source files were changed.\n')
    print(json.dumps({'summary': report['summary'], 'findings': report['findings'][:90], 'code_paths': report['code_paths'][:70]}, indent=2))
    if args.check and report['findings']:
        parser.exit(1, 'docs audit: repair the listed current links or structured files, then rerun. Historical prose and illustrative code-path hints are not failures.\n')

if __name__ == '__main__':
    main()
