"""Render MCP documentation from the canonical, closed JSON schema catalog."""
from __future__ import annotations

import hashlib
import json
from typing import Any

from doc_schema import ContractError, cell, fields_table, operations, resolve_schema

T = chr(96)


def generate_markdown(document: dict[str, Any]) -> str:
    items = operations(document)
    meta = document["x-axon"]
    if meta.get("projection_values") != ["legacy", "atomic", "both"]:
        raise ContractError("MCP projection contract changed; update the renderer's projection explanation")
    encoded = json.dumps(document, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()
    lines = [
        "# Axon MCP Tool Schema",
        "",
        "<!-- AUTO-GENERATED by scripts/generate_mcp_schema_doc.py; do not edit manually -->",
        f"<!-- canonical JSON SHA-256: {hashlib.sha256(encoded).hexdigest()} -->",
        "",
        "[MCP overview](overview.md) · [Configuration](../../guides/configuration.md) · [Machine-readable contract](tool-schema.json)",
        "",
        "## Contract",
        "",
        f"Generated from {T}tool-schema.json{T}, exported by {T}cargo xtask schemas mcp{T} from the live action and operation registries. This includes system and watch requests, not just the primary AxonRequest enum.",
        f"Contract version: {T}{cell(meta.get('contract_version'))}{T}. The catalog contains **{len(items)} atomic operations** across **{meta['live_action_count']} action families**.",
        "",
        "## Tool Projections",
        "",
        f"The configured default is {T}{cell(meta['projection_default'])}{T}. Tool discovery depends on startup projection and authorization; a schema inventory is not proof that a particular running deployment advertises it.",
        "",
        "| Projection | Operation surface |",
        "|---|---|",
        f"| legacy | Aggregate {T}axon{T} tool with action and optional subaction selectors |",
        f"| atomic | {len(items)} named operation tools; selectors are fixed by the tool and must not be supplied as arguments |",
        "| both | Aggregate and atomic operation tools |",
        "",
        f"The auxiliary {T}axon_status_dashboard{T} tool and {T}ui://axon/status-dashboard{T} resource are separate presentation surfaces, retained by the router. They are not counted as atomic business operations. Verify the complete runtime tools/list and resource catalog against a matching build.",
        "",
        "Source: [router composition](../../../crates/axon-mcp/src/server/projection.rs), [server](../../../crates/axon-mcp/src/server.rs), and [canonical schema registry](../../../crates/axon-mcp/src/schema_registry.rs).",
        "",
        "## Operation Catalog",
        "",
        "Names, selectors, scope, and task support below come from the exported operation registry. A null scope means no additional operation-specific scope, not disabled transport authentication. Metadata never substitutes for authorization or handler validation.",
        "",
        "| Atomic tool | Aggregate action | Subaction | Scope | Read only | Task support |",
        "|---|---|---|---|---|---|",
    ]
    for item in items:
        lines.append("| " + " | ".join(cell(item.get(key, "")) if item.get(key) is not None else "(none)" for key in ("name", "action", "subaction", "required_scope", "read_only", "task_support")) + " |")
    lines += ["", "## Task-Augmented Calls", "", "The following operations declare task support in the canonical registry:", ""]
    supported = [item for item in items if item["task_support"] != "forbidden"]
    lines += [f"- {T}{cell(item['name'])}{T}: {cell(item['task_support'])}." for item in supported] or ["No task starts are advertised by this catalog."]
    lines += [
        "",
        "Task opt-in and lifecycle use negotiated protocol metadata, not fields added to the operation's argument map. Ordinary source job IDs and protocol task handles are distinct projections over the durable job runtime. A returned handle is not completed work.",
        "See [task behavior and polling](overview.md#task-augmented-calls) and [task implementation](../../../crates/axon-mcp/src/server/tasks.rs) for version-specific calls, cancellation, and completion semantics.",
        "",
        "## Canonical Success Envelope",
        "",
        "This table is rendered from the exported AxonToolResponse schema. Required-by-schema describes that schema, not a promise that conditionally serialized empty fields occur in every response. The full contract retains nested references and constraints.",
        "",
    ]
    lines += fields_table(document, {"$ref": "#/$defs/AxonToolResponse"})
    lines += [
        "",
        "## Parser Rules",
        "",
        "The aggregate route validates the canonical action/subaction request. Atomic tools omit those fixed selectors and reject attempts to override them. Input tables below describe the focused atomic schema; aggregate callers must additionally provide the operation's action and applicable subaction.",
        "Required fields, defaults, enum alternatives, and nullability are generated from JSON Schema. Optional schema fields can still be conditionally required by a handler. No implicit privilege, provider authorization, or execution permission follows from discovery.",
        "",
        "## Input Schemas",
        "",
    ]
    for item in items:
        schema = resolve_schema(document, item["inputSchema"])
        lines += [f"### {item['name']}", "", cell(item["description"]), "", f"Additional properties: {T}{json.dumps(schema.get('additionalProperties', True))}{T}.", ""]
        lines += fields_table(document, schema)
        lines.append("")
    lines += [
        "## Response Policy and Artifacts",
        "",
        "Use the returned opaque artifact_id with the artifacts operations to inspect or read retained output. A server filesystem location is not a client-accessible artifact reference. Read response_mode's actual enum/default from the input schema instead of assuming every action has the same inlining policy.",
        "",
        "[MCP overview](overview.md) covers response handling and resources. [Artifact implementation](../../../crates/axon-mcp/src/server/artifacts.rs) owns storage and retrieval. Large results, partial results, and job starts must retain their reported status; do not replay a write to recover missing output.",
        "",
        "## Generation and Verification",
        "",
        "~~~bash",
        "cargo xtask generated-contracts refresh",
        "cargo xtask generated-contracts check",
        "python3 scripts/generate_mcp_schema_doc.py --check",
        "~~~",
        "",
        "The renderer validates source-input hashes and rejects malformed/duplicate operations and unresolved input references. It does not parse Rust with a second hand-maintained type map. Update the owning typed schema or renderer, then regenerate; never patch this output to make a drift check pass.",
    ]
    return "\n".join(lines) + "\n"
