use super::*;

#[test]
fn every_emitted_docs_command_is_accepted_by_the_actual_cli() {
    use clap::Parser;
    for family in DocsFamily::ALL {
        let input = SourceInput {
            path: PathBuf::from("docs/reference/input.json"),
            checksum: "sha256:test".to_owned(),
        };
        let output =
            render_json_reference(family, &input, &serde_json::json!({"title":"Example"})).unwrap();
        assert!(output.starts_with(&format!(
            "<!-- generated by cargo xtask docs generate --family {};",
            family.slug()
        )));
        assert!(
            crate::Cli::try_parse_from(["xtask", "docs", "generate", "--family", family.slug()])
                .is_ok()
        );
    }
}

#[test]
fn non_object_contract_is_not_rendered_as_a_successful_empty_reference() {
    let input = SourceInput {
        path: PathBuf::from("input.json"),
        checksum: "sha256:test".to_owned(),
    };
    assert!(render_json_reference(DocsFamily::ApiDto, &input, &serde_json::json!([])).is_err());
}

#[test]
fn docs_family_inventory_matches_the_contract() {
    let slugs = DocsFamily::ALL.map(DocsFamily::slug);
    assert_eq!(
        slugs,
        [
            "cli",
            "cli-help",
            "openapi",
            "mcp",
            "api-dto",
            "api-enums",
            "errors",
            "events",
            "config",
            "env",
            "schema",
            "memory",
            "providers",
            "presentation",
            "schemas",
            "new-source",
        ]
    );
}
