use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use clap::ValueEnum;
use sha2::{Digest, Sha256};

use super::artifact::{DocsArtifactSet, GeneratedDocArtifact};

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, ValueEnum)]
#[value(rename_all = "kebab-case")]
pub enum DocsFamily {
    ApiDto,
    ApiEnums,
    Adapters,
    Events,
    Providers,
    Schema,
}

impl DocsFamily {
    pub const ALL: [Self; 6] = [
        Self::ApiDto,
        Self::ApiEnums,
        Self::Adapters,
        Self::Events,
        Self::Providers,
        Self::Schema,
    ];

    pub const fn slug(self) -> &'static str {
        match self {
            Self::ApiDto => "api-dto",
            Self::ApiEnums => "api-enums",
            Self::Adapters => "adapters",
            Self::Events => "events",
            Self::Providers => "providers",
            Self::Schema => "schema",
        }
    }

    const fn input_path(self) -> &'static str {
        match self {
            Self::ApiDto | Self::ApiEnums => "docs/reference/api/schemas.json",
            Self::Adapters => "docs/reference/sources/adapter-scopes.json",
            Self::Events => "docs/reference/runtime/events.schema.json",
            Self::Providers => "docs/reference/runtime/provider-capabilities.schema.json",
            Self::Schema => "docs/reference/runtime/database-schema.json",
        }
    }

    const fn output_path(self) -> &'static str {
        match self {
            Self::ApiDto => "docs/reference/api/dto.md",
            Self::ApiEnums => "docs/reference/api/enums.md",
            Self::Adapters => "docs/reference/sources/adapter-scopes.md",
            Self::Events => "docs/reference/runtime/observability.md",
            Self::Providers => "docs/reference/runtime/providers.md",
            Self::Schema => "docs/reference/runtime/schema.md",
        }
    }

    const fn title(self) -> &'static str {
        match self {
            Self::ApiDto => "API DTO Reference",
            Self::ApiEnums => "API Enum Reference",
            Self::Adapters => "Source Adapter Reference",
            Self::Events => "Runtime Event Reference",
            Self::Providers => "Provider Capability Reference",
            Self::Schema => "Runtime Database Schema",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SourceInput {
    pub path: PathBuf,
    pub checksum: String,
}

pub trait DocsFamilyGenerator {
    fn family(&self) -> DocsFamily;
    fn source_inputs(&self, root: &Path) -> Result<Vec<SourceInput>>;
    fn generate(&self, root: &Path) -> Result<DocsArtifactSet>;
}

pub struct JsonFamilyGenerator(pub DocsFamily);

impl DocsFamilyGenerator for JsonFamilyGenerator {
    fn family(&self) -> DocsFamily {
        self.0
    }

    fn source_inputs(&self, root: &Path) -> Result<Vec<SourceInput>> {
        let relative = PathBuf::from(self.0.input_path());
        let content = std::fs::read(root.join(&relative)).with_context(|| {
            format!(
                "docs {} source input is missing: {}",
                self.0.slug(),
                relative.display()
            )
        })?;
        Ok(vec![SourceInput {
            path: relative,
            checksum: format!("sha256:{:x}", Sha256::digest(&content)),
        }])
    }

    fn generate(&self, root: &Path) -> Result<DocsArtifactSet> {
        let source_inputs = self.source_inputs(root)?;
        let input = &source_inputs[0];
        let raw = std::fs::read_to_string(root.join(&input.path))?;
        let json: serde_json::Value = serde_json::from_str(&raw)
            .with_context(|| format!("docs {} source input is not valid JSON", self.0.slug()))?;
        let rendered = render_json_reference(self.0, input, &json)?;
        let artifact = GeneratedDocArtifact::new(self.0.output_path(), rendered, self.0.slug())?;
        Ok(DocsArtifactSet {
            family: self.0,
            artifacts: vec![artifact],
            source_inputs,
        })
    }
}

fn render_json_reference(
    family: DocsFamily,
    input: &SourceInput,
    value: &serde_json::Value,
) -> Result<String> {
    let mut content = format!(
        "<!-- generated by cargo xtask docs {}; do not edit directly -->\n<!-- source inputs: {} -->\n\n# {}\n\nGenerated from [`{}`](../../../{}). The linked JSON artifact is the complete machine-readable contract; this page is its deterministic human index.\n\n## Source Manifest\n\n| Path | SHA-256 |\n|---|---|\n| `{}` | `{}` |\n\n## Top-Level Inventory\n\n{}\n\n## Named Definitions\n\n{}\n",
        family.slug(),
        input.checksum,
        family.title(),
        input.path.display(),
        input.path.display(),
        input.path.display(),
        input.checksum,
        top_level_inventory(value),
        named_definitions(value),
    );
    content.truncate(content.trim_end().len());
    content.push('\n');
    if content.lines().count() < 8 {
        bail!(
            "docs {} renderer produced incomplete content",
            family.slug()
        );
    }
    Ok(content)
}

fn top_level_inventory(value: &serde_json::Value) -> String {
    let Some(object) = value.as_object() else {
        return "The source artifact is not a JSON object.\n".to_owned();
    };
    let mut rows = object
        .iter()
        .map(|(key, value)| format!("| `{key}` | {} |", value_shape(value)))
        .collect::<Vec<_>>();
    rows.sort();
    format!("| Field | Shape |\n|---|---|\n{}", rows.join("\n"))
}

fn named_definitions(value: &serde_json::Value) -> String {
    let Some(object) = value.as_object() else {
        return "No named definitions.\n".to_owned();
    };
    let mut names = ["definitions", "$defs", "tables", "properties", "components"]
        .into_iter()
        .flat_map(|key| named_members(object.get(key)))
        .collect::<Vec<_>>();
    names.sort();
    names.dedup();
    if names.is_empty() {
        "No named definitions in this artifact.\n".to_owned()
    } else {
        names
            .into_iter()
            .map(|name| format!("- `{name}`"))
            .collect::<Vec<_>>()
            .join("\n")
            + "\n"
    }
}

fn named_members(value: Option<&serde_json::Value>) -> Vec<String> {
    match value {
        Some(serde_json::Value::Object(values)) => values.keys().cloned().collect(),
        Some(serde_json::Value::Array(values)) => values
            .iter()
            .filter_map(|value| {
                value
                    .get("name")
                    .or_else(|| value.get("table"))
                    .and_then(serde_json::Value::as_str)
                    .map(str::to_owned)
            })
            .collect(),
        _ => Vec::new(),
    }
}

fn value_shape(value: &serde_json::Value) -> String {
    match value {
        serde_json::Value::Array(values) => format!("array ({})", values.len()),
        serde_json::Value::Object(values) => format!("object ({})", values.len()),
        serde_json::Value::String(_) => "string".to_owned(),
        serde_json::Value::Number(_) => "number".to_owned(),
        serde_json::Value::Bool(_) => "boolean".to_owned(),
        serde_json::Value::Null => "null".to_owned(),
    }
}

pub fn generator_for(family: DocsFamily) -> Box<dyn DocsFamilyGenerator> {
    Box::new(JsonFamilyGenerator(family))
}
