use super::*;
use std::fs;

fn seed(root: &Path) {
    fs::create_dir_all(root.join("docs/reference/api")).unwrap();
    fs::write(
        root.join("docs/reference/api/schemas.json"),
        serde_json::to_string_pretty(&serde_json::json!({
            "title": "Axon API",
            "definitions": {"SourceRequest": {"type": "object"}},
            "x-axon": {
                "generated_by": "cargo xtask schemas api",
                "source_inputs": [{
                    "path": "crates/axon-api/src/source.rs",
                    "kind": "rust_module",
                    "checksum": "sha256:source"
                }]
            }
        }))
        .unwrap(),
    )
    .unwrap();
}

fn args(check: bool) -> DocsGenerateArgs {
    DocsGenerateArgs {
        check,
        family: Some(DocsFamily::ApiDto),
        ..Default::default()
    }
}

#[test]
fn generate_writes_complete_artifact() {
    let dir = tempfile::tempdir().unwrap();
    seed(dir.path());
    run(dir.path(), &args(false)).unwrap();

    let md = fs::read_to_string(dir.path().join("docs/reference/api/dto.md")).unwrap();
    assert!(md.starts_with("<!-- generated by cargo xtask docs api-dto;"));
    assert!(md.contains("# API DTO Reference"));
    assert!(md.contains("`SourceRequest`"));

    let manifest =
        fs::read_to_string(dir.path().join("docs/reference/source-input-manifest.json")).unwrap();
    assert!(manifest.contains("\"family\": \"api\""));
    assert!(manifest.contains("crates/axon-api/src/source.rs"));
}

#[test]
fn generate_twice_is_byte_identical() {
    let dir = tempfile::tempdir().unwrap();
    seed(dir.path());
    run(dir.path(), &args(false)).unwrap();
    let first = fs::read_to_string(dir.path().join("docs/reference/api/dto.md")).unwrap();
    run(dir.path(), &args(false)).unwrap();
    let second = fs::read_to_string(dir.path().join("docs/reference/api/dto.md")).unwrap();
    assert_eq!(first, second);
}

#[test]
fn check_compares_full_body_without_writing() {
    let dir = tempfile::tempdir().unwrap();
    seed(dir.path());
    assert!(run(dir.path(), &args(true)).is_err());
    run(dir.path(), &args(false)).unwrap();
    let path = dir.path().join("docs/reference/api/dto.md");
    fs::write(
        &path,
        "<!-- generated by cargo xtask docs api-dto; do not edit directly -->\n",
    )
    .unwrap();
    assert!(run(dir.path(), &args(true)).is_err());
}

#[test]
fn check_detects_source_input_manifest_drift() {
    let dir = tempfile::tempdir().unwrap();
    seed(dir.path());
    run(dir.path(), &args(false)).unwrap();
    fs::write(
        dir.path().join("docs/reference/source-input-manifest.json"),
        "{\"families\": []}\n",
    )
    .unwrap();
    let error = run(dir.path(), &args(true)).unwrap_err().to_string();
    assert!(error.contains("source-input-manifest.json differs"));
}

#[test]
fn missing_source_input_is_rejected() {
    let dir = tempfile::tempdir().unwrap();
    assert!(run(dir.path(), &args(false)).is_err());
}

#[test]
fn secret_and_absolute_path_canaries_are_rejected() {
    for content in [
        "# Generated\nAuthorization: Bearer synthetic-secret-value\n",
        "# Generated\nSee /home/operator/private.txt\n",
    ] {
        let error =
            GeneratedDocArtifact::new("docs/reference/api/dto.md", content.to_owned(), "test")
                .unwrap_err()
                .to_string();
        assert!(error.contains("secret-shaped") || error.contains("absolute filesystem path"));
    }
}

#[test]
fn empty_and_header_only_artifacts_are_rejected() {
    for content in ["", "<!-- generated by cargo xtask docs -->\n"] {
        let error =
            GeneratedDocArtifact::new("docs/reference/api/dto.md", content.to_owned(), "test")
                .unwrap_err()
                .to_string();
        assert!(error.contains("empty/header-only"));
    }
}

#[test]
fn generated_artifact_paths_must_be_relative() {
    let error = GeneratedDocArtifact::new("/tmp/generated.md", "# generated\n".to_owned(), "test")
        .unwrap_err()
        .to_string();
    assert!(error.contains("unsafe artifact path"));
}
