use super::*;
use std::fs;

fn seed(root: &std::path::Path) {
    fs::create_dir_all(root.join("docs/reference/api")).unwrap();
    fs::write(
        root.join("docs/reference/api/schemas.json"),
        serde_json::to_string_pretty(&serde_json::json!({
            "title": "Axon API",
            "definitions": {"SourceRequest": {"type": "object"}}
        }))
        .unwrap(),
    )
    .unwrap();
}

fn args(check: bool) -> DocsGenerateArgs {
    DocsGenerateArgs {
        check,
        family: Some(DocsFamily::ApiDto),
        ..Default::default()
    }
}

#[test]
fn generate_writes_complete_artifact() {
    let dir = tempfile::tempdir().unwrap();
    seed(dir.path());
    run(dir.path(), &args(false)).unwrap();

    let md = fs::read_to_string(dir.path().join("docs/reference/api/dto.md")).unwrap();
    assert!(md.starts_with("<!-- generated by cargo xtask docs api-dto;"));
    assert!(md.contains("# API DTO Reference"));
    assert!(md.contains("`SourceRequest`"));
}

#[test]
fn generate_twice_is_byte_identical() {
    let dir = tempfile::tempdir().unwrap();
    seed(dir.path());
    run(dir.path(), &args(false)).unwrap();
    let first = fs::read_to_string(dir.path().join("docs/reference/api/dto.md")).unwrap();
    run(dir.path(), &args(false)).unwrap();
    let second = fs::read_to_string(dir.path().join("docs/reference/api/dto.md")).unwrap();
    assert_eq!(first, second);
}

#[test]
fn check_compares_full_body_without_writing() {
    let dir = tempfile::tempdir().unwrap();
    seed(dir.path());
    assert!(run(dir.path(), &args(true)).is_err());
    run(dir.path(), &args(false)).unwrap();
    let path = dir.path().join("docs/reference/api/dto.md");
    fs::write(
        &path,
        "<!-- generated by cargo xtask docs api-dto; do not edit directly -->\n",
    )
    .unwrap();
    assert!(run(dir.path(), &args(true)).is_err());
}

#[test]
fn missing_source_input_is_rejected() {
    let dir = tempfile::tempdir().unwrap();
    assert!(run(dir.path(), &args(false)).is_err());
}
