use super::exceptions::{ManifestException, ReachException};

const TASK_6: &str = "axon_rust-nl7au (Task 6 scheduler cutover)";
const TASK_7: &str = "axon_rust-drahp (Task 7 pipeline collapse)";

macro_rules! reach {
    ($path:literal, $rule:literal, $owner:expr, $count:literal) => {
        ReachException {
            path: $path,
            rule: $rule,
            owner: $owner,
            expected_count: $count,
        }
    };
}

pub(super) const MANIFEST_EXCEPTIONS: &[ManifestException] = &[];

#[rustfmt::skip]
pub(super) const REACH_EXCEPTIONS: &[ReachException] = &[
    reach!("crates/axon-services/src/screenshot.rs", "reach:axon_adapters::web_engine", TASK_7, 2),
    reach!("crates/axon-services/src/endpoints/capture.rs", "reach:axon_adapters::web_engine", TASK_7, 1),
    reach!("crates/axon-cli/src/commands/resources/graph.rs", "provider-type:GraphStore", TASK_6, 1),
    reach!("crates/axon-cli/src/commands/resources/graph.rs", "provider-op:GraphStore::get_edge", TASK_6, 1),
    reach!("crates/axon-cli/src/commands/resources/graph.rs", "provider-op:GraphStore::query", TASK_6, 1),
    reach!("crates/axon-cli/src/commands/resources/graph.rs", "provider-op:GraphStore::resolve", TASK_6, 1),
    reach!("crates/axon-mcp/src/server/artifacts/respond.rs", "provider-type:ArtifactStore", TASK_6, 1),
    reach!("crates/axon-mcp/src/server/artifacts/respond.rs", "provider-method:put_bytes", TASK_6, 1),
    reach!("crates/axon-mcp/src/server/handlers_graph.rs", "provider-type:GraphStore", TASK_6, 1),
    reach!("crates/axon-mcp/src/server/handlers_graph.rs", "provider-op:GraphStore::get_edge", TASK_6, 1),
    reach!("crates/axon-mcp/src/server/handlers_graph.rs", "provider-op:GraphStore::query", TASK_6, 1),
    reach!("crates/axon-mcp/src/server/handlers_graph.rs", "provider-op:GraphStore::resolve", TASK_6, 1),
    reach!("crates/axon-web/src/server/handlers/graph.rs", "provider-op:GraphStore::get_edge", TASK_6, 1),
    reach!("crates/axon-web/src/server/handlers/graph.rs", "provider-op:GraphStore::query", TASK_6, 1),
    reach!("crates/axon-web/src/server/handlers/graph.rs", "provider-op:GraphStore::resolve", TASK_6, 1),
    reach!("crates/axon-services/src/context.rs", "provider-type:ArtifactStore", TASK_6, 2),
    reach!("crates/axon-services/src/context.rs", "provider-type:EmbeddingProvider", TASK_6, 2),
    reach!("crates/axon-services/src/context.rs", "provider-type:FetchProvider", TASK_6, 2),
    reach!("crates/axon-services/src/context.rs", "provider-type:RenderProvider", TASK_6, 2),
    reach!("crates/axon-services/src/context.rs", "provider-type:VectorStore", TASK_6, 2),
    reach!("crates/axon-services/src/debug.rs", "provider-op:axon_llm::complete_text", TASK_6, 1),
    reach!("crates/axon-services/src/graph.rs", "provider-type:GraphStore", TASK_6, 3),
    reach!("crates/axon-services/src/graph.rs", "provider-method:node_edges", TASK_6, 1),
    reach!("crates/axon-services/src/graph.rs", "provider-method:nodes_for_source", TASK_6, 1),
    reach!("crates/axon-services/src/memory/import_export.rs", "provider-type:ArtifactStore", TASK_6, 1),
    reach!("crates/axon-services/src/memory/import_export.rs", "provider-method:put_bytes", TASK_6, 1),
    reach!("crates/axon-services/src/memory/store.rs", "provider-handle:embedding_provider", TASK_6, 1),
    reach!("crates/axon-services/src/memory/store.rs", "provider-handle:vector_store", TASK_6, 1),
    reach!("crates/axon-services/src/memory/store.rs", "provider-type:GraphStore", TASK_6, 1),
    reach!("crates/axon-services/src/memory/store.rs", "provider-op:axon_llm::complete_text", TASK_6, 1),
    reach!("crates/axon-services/src/prune.rs", "provider-handle:vector_store", TASK_6, 2),
    reach!("crates/axon-services/src/prune.rs", "provider-type:VectorStore", TASK_6, 2),
    reach!("crates/axon-services/src/query/code_search.rs", "provider-method:embed", TASK_6, 1),
    reach!("crates/axon-services/src/query/synthesis/completion.rs", "provider-op:axon_llm::complete_streaming", TASK_6, 1),
    reach!("crates/axon-services/src/query/synthesis/completion.rs", "provider-op:axon_llm::complete_text", TASK_6, 1),
    reach!("crates/axon-services/src/scrape.rs", "provider-type:ArtifactStore", TASK_6, 1),
    reach!("crates/axon-services/src/scrape.rs", "provider-method:put_bytes", TASK_6, 1),
    reach!("crates/axon-services/src/screenshot.rs", "provider-type:ArtifactStore", TASK_6, 1),
    reach!("crates/axon-services/src/screenshot.rs", "provider-method:put_bytes", TASK_6, 1),
    reach!("crates/axon-services/src/search/provider.rs", "provider-type:SearchProvider", TASK_6, 1),
    reach!("crates/axon-services/src/service_traits/provider_service.rs", "provider-handle:vector_store", TASK_6, 1),
    reach!("crates/axon-services/src/source.rs", "provider-handle:artifact_store", TASK_6, 1),
    reach!("crates/axon-services/src/source.rs", "provider-handle:vector_store", TASK_6, 1),
    reach!("crates/axon-services/src/source.rs", "provider-type:GraphStore", TASK_6, 2),
    reach!("crates/axon-services/src/source/dispatch/tool_artifacts.rs", "provider-handle:artifact_store", TASK_6, 1),
    reach!("crates/axon-services/src/source/prune.rs", "provider-handle:graph_store", TASK_6, 1),
    reach!("crates/axon-services/src/source/prune.rs", "provider-handle:vector_store", TASK_6, 1),
    reach!("crates/axon-services/src/source/prune.rs", "provider-type:ArtifactStore", TASK_6, 2),
    reach!("crates/axon-services/src/source/prune.rs", "provider-type:GraphStore", TASK_6, 4),
    reach!("crates/axon-services/src/source/prune.rs", "provider-type:VectorStore", TASK_6, 5),
    reach!("crates/axon-services/src/source/prune/drain_ops.rs", "provider-handle:graph_store", TASK_6, 1),
    reach!("crates/axon-services/src/source/prune/drain_ops.rs", "provider-handle:vector_store", TASK_6, 1),
    reach!("crates/axon-services/src/source/prune/drain_ops.rs", "provider-method:delete_edges", TASK_6, 1),
    reach!("crates/axon-services/src/source/prune/drain_ops.rs", "provider-method:delete_nodes", TASK_6, 1),
    reach!("crates/axon-services/src/source/prune/drain_ops.rs", "provider-type:ArtifactStore", TASK_6, 2),
    reach!("crates/axon-services/src/source/prune/drain_ops.rs", "provider-type:GraphStore", TASK_6, 1),
    reach!("crates/axon-services/src/source/prune/drain_ops.rs", "provider-type:VectorStore", TASK_6, 1),
    reach!("crates/axon-services/src/search/synthesis.rs", "provider-op:axon_llm::complete_streaming", TASK_6, 1),
    reach!("crates/axon-services/src/service_traits/ask_service.rs", "provider-op:axon_llm::complete_text", TASK_6, 1),
    reach!("crates/axon-services/src/service_traits/ask_service.rs", "provider-op:axon_llm::complete_streaming", TASK_6, 1),
    reach!("crates/axon-services/src/summarize.rs", "provider-op:axon_llm::complete_streaming", TASK_6, 1),
    reach!("crates/axon-services/src/endpoints.rs", "provider-type:NetworkCaptureProvider", TASK_6, 3),
    reach!("crates/axon-services/src/uploads.rs", "provider-type:ArtifactStore", TASK_6, 1),
    reach!("crates/axon-services/src/uploads.rs", "provider-method:put_bytes", TASK_6, 1),
    reach!("crates/axon-services/src/uploads/cleanup.rs", "provider-type:ArtifactStore", TASK_6, 1),
    reach!("crates/axon-cli/src/commands/resources/graph.rs", "provider-type:SqliteGraphStore", TASK_6, 1),
    reach!("crates/axon-mcp/src/server/artifacts/respond.rs", "provider-op:FileArtifactStore::new", TASK_6, 1),
    reach!("crates/axon-mcp/src/server/artifacts/respond.rs", "provider-type:FileArtifactStore", TASK_6, 1),
    reach!("crates/axon-mcp/src/server/handlers_graph.rs", "provider-type:SqliteGraphStore", TASK_6, 1),
    reach!("crates/axon-services/src/endpoints.rs", "provider-type:ChromeNetworkCapture", TASK_6, 2),
    reach!("crates/axon-services/src/graph.rs", "provider-method:get_node", TASK_6, 1),
    reach!("crates/axon-services/src/graph.rs", "provider-method:query", TASK_6, 1),
    reach!("crates/axon-services/src/graph.rs", "provider-op:SqliteGraphStore::from_pool", TASK_6, 1),
    reach!("crates/axon-services/src/graph.rs", "provider-type:SqliteGraphStore", TASK_6, 2),
    reach!("crates/axon-services/src/memory.rs", "provider-type:SqliteGraphStore", TASK_6, 1),
    reach!("crates/axon-services/src/memory/import_export.rs", "provider-op:FileArtifactStore::new", TASK_6, 1),
    reach!("crates/axon-services/src/memory/import_export.rs", "provider-type:FileArtifactStore", TASK_6, 1),
    reach!("crates/axon-services/src/memory/store.rs", "provider-op:SqliteGraphStore::from_pool", TASK_6, 1),
    reach!("crates/axon-services/src/prune.rs", "provider-method:count_collection_points", TASK_6, 1),
    reach!("crates/axon-services/src/prune.rs", "provider-method:delete", TASK_6, 1),
    reach!("crates/axon-services/src/prune.rs", "provider-op:QdrantVectorStore::new", TASK_6, 2),
    reach!("crates/axon-services/src/prune.rs", "provider-type:QdrantVectorStore", TASK_6, 1),
    reach!("crates/axon-services/src/query/retrieve.rs", "provider-op:QdrantVectorStore::new", TASK_6, 1),
    reach!("crates/axon-services/src/query/retrieve.rs", "provider-type:QdrantVectorStore", TASK_6, 2),
    reach!("crates/axon-services/src/query/suggest.rs", "provider-method:facet", TASK_6, 1),
    reach!("crates/axon-services/src/query/suggest.rs", "provider-method:scroll_pages", TASK_6, 1),
    reach!("crates/axon-services/src/query/suggest.rs", "provider-op:QdrantVectorStore::new", TASK_6, 1),
    reach!("crates/axon-services/src/query/suggest.rs", "provider-type:QdrantVectorStore", TASK_6, 2),
    reach!("crates/axon-services/src/reset/execution.rs", "provider-op:QdrantVectorStore::invalidate_collection_spec_cache", TASK_6, 1),
    reach!("crates/axon-services/src/scrape.rs", "provider-op:FileArtifactStore::new", TASK_6, 1),
    reach!("crates/axon-services/src/scrape.rs", "provider-type:FileArtifactStore", TASK_6, 1),
    reach!("crates/axon-services/src/screenshot.rs", "provider-op:FileArtifactStore::new", TASK_6, 1),
    reach!("crates/axon-services/src/screenshot.rs", "provider-type:FileArtifactStore", TASK_6, 1),
    reach!("crates/axon-services/src/search/provider.rs", "provider-method:search", TASK_6, 1),
    reach!("crates/axon-services/src/search/provider.rs", "provider-op:SearxngSearchProvider::new", TASK_6, 1),
    reach!("crates/axon-services/src/search/provider.rs", "provider-op:TavilySearchProvider::new", TASK_6, 1),
    reach!("crates/axon-services/src/search/provider.rs", "provider-type:SearxngSearchProvider", TASK_6, 2),
    reach!("crates/axon-services/src/search/provider.rs", "provider-type:TavilySearchProvider", TASK_6, 3),
    reach!("crates/axon-services/src/source.rs", "provider-method:as_ref", TASK_6, 2),
    reach!("crates/axon-services/src/source/dispatch/tool_artifacts.rs", "provider-method:put", TASK_6, 1),
    reach!("crates/axon-services/src/source/prune/drain_ops.rs", "provider-method:delete", TASK_6, 2),
    reach!("crates/axon-services/src/system/domains.rs", "provider-method:domain_has_indexed_url", TASK_6, 1),
    reach!("crates/axon-services/src/system/domains.rs", "provider-method:facet", TASK_6, 1),
    reach!("crates/axon-services/src/system/domains.rs", "provider-method:scroll_pages", TASK_6, 1),
    reach!("crates/axon-services/src/system/domains.rs", "provider-op:QdrantVectorStore::new", TASK_6, 3),
    reach!("crates/axon-services/src/system/domains.rs", "provider-type:QdrantVectorStore", TASK_6, 2),
    reach!("crates/axon-services/src/system/sources.rs", "provider-method:facet", TASK_6, 1),
    reach!("crates/axon-services/src/system/sources.rs", "provider-method:urls_for_domain_page", TASK_6, 1),
    reach!("crates/axon-services/src/system/sources.rs", "provider-op:QdrantVectorStore::new", TASK_6, 2),
    reach!("crates/axon-services/src/system/sources.rs", "provider-type:QdrantVectorStore", TASK_6, 2),
    reach!("crates/axon-services/src/system/stats.rs", "provider-op:QdrantVectorStore::new", TASK_6, 1),
    reach!("crates/axon-services/src/system/stats.rs", "provider-type:QdrantVectorStore", TASK_6, 1),
    reach!("crates/axon-services/src/system/stats/qdrant_fetch.rs", "provider-method:count_collection_points", TASK_6, 1),
    reach!("crates/axon-services/src/system/stats/qdrant_fetch.rs", "provider-method:scroll_pages", TASK_6, 2),
    reach!("crates/axon-services/src/system/stats/qdrant_fetch.rs", "provider-type:QdrantVectorStore", TASK_6, 4),
    reach!("crates/axon-services/src/uploads.rs", "provider-op:FileArtifactStore::new", TASK_6, 1),
    reach!("crates/axon-services/src/uploads.rs", "provider-type:FileArtifactStore", TASK_6, 2),
    reach!("crates/axon-web/src/server/handlers/graph.rs", "provider-type:SqliteGraphStore", TASK_6, 1),
];
