use super::exceptions::{ManifestException, ReachException};

const TASK_2: &str = "axon_rust-jc20j (Task 2 transport cutover)";
const TASK_6: &str = "axon_rust-nl7au (Task 6 scheduler cutover)";
const TASK_7: &str = "axon_rust-drahp (Task 7 pipeline collapse)";

macro_rules! reach {
    ($path:literal, $rule:literal, $owner:expr, $count:literal) => {
        ReachException {
            path: $path,
            rule: $rule,
            owner: $owner,
            expected_count: $count,
        }
    };
}

pub(super) const MANIFEST_EXCEPTIONS: &[ManifestException] = &[
    ManifestException {
        path: "crates/axon-cli/Cargo.toml",
        dependency: "axon-adapters",
        table: "dependencies",
        owner: TASK_2,
        expected_count: 1,
    },
    ManifestException {
        path: "crates/axon-web/Cargo.toml",
        dependency: "axon-llm",
        table: "dependencies",
        owner: TASK_2,
        expected_count: 1,
    },
];

#[rustfmt::skip]
pub(super) const REACH_EXCEPTIONS: &[ReachException] = &[
    reach!("crates/axon-web/src/server/handlers/chat.rs", "reach:axon_llm", TASK_2, 5),
    reach!("crates/axon-web/src/server/handlers/chat_stream.rs", "reach:axon_llm", TASK_2, 6),
    reach!("crates/axon-services/src/scrape.rs", "reach:axon_adapters::web_engine", TASK_7, 3),
    reach!("crates/axon-services/src/screenshot.rs", "reach:axon_adapters::web_engine", TASK_7, 2),
    reach!("crates/axon-services/src/endpoints/capture.rs", "reach:axon_adapters::web_engine", TASK_7, 1),
    reach!("crates/axon-cli/src/commands/resources/graph.rs", "provider-type:GraphStore", TASK_6, 1),
    reach!("crates/axon-cli/src/commands/resources/graph.rs", "provider-op:GraphStore::get_edge", TASK_6, 1),
    reach!("crates/axon-cli/src/commands/resources/graph.rs", "provider-op:GraphStore::query", TASK_6, 1),
    reach!("crates/axon-cli/src/commands/resources/graph.rs", "provider-op:GraphStore::resolve", TASK_6, 1),
    reach!("crates/axon-mcp/src/server/artifacts/respond.rs", "provider-type:ArtifactStore", TASK_6, 1),
    reach!("crates/axon-mcp/src/server/artifacts/respond.rs", "provider-method:put_bytes", TASK_6, 1),
    reach!("crates/axon-mcp/src/server/handlers_graph.rs", "provider-type:GraphStore", TASK_6, 1),
    reach!("crates/axon-mcp/src/server/handlers_graph.rs", "provider-op:GraphStore::get_edge", TASK_6, 1),
    reach!("crates/axon-mcp/src/server/handlers_graph.rs", "provider-op:GraphStore::query", TASK_6, 1),
    reach!("crates/axon-mcp/src/server/handlers_graph.rs", "provider-op:GraphStore::resolve", TASK_6, 1),
    reach!("crates/axon-web/src/server/handlers/graph.rs", "provider-op:GraphStore::get_edge", TASK_6, 1),
    reach!("crates/axon-web/src/server/handlers/graph.rs", "provider-op:GraphStore::query", TASK_6, 1),
    reach!("crates/axon-web/src/server/handlers/graph.rs", "provider-op:GraphStore::resolve", TASK_6, 1),
    reach!("crates/axon-web/src/server/handlers/chat_stream.rs", "provider-op:axon_llm::complete_streaming", TASK_2, 1),
    reach!("crates/axon-services/src/context.rs", "provider-type:ArtifactStore", TASK_6, 2),
    reach!("crates/axon-services/src/context.rs", "provider-type:EmbeddingProvider", TASK_6, 2),
    reach!("crates/axon-services/src/context.rs", "provider-type:FetchProvider", TASK_6, 2),
    reach!("crates/axon-services/src/context.rs", "provider-type:RenderProvider", TASK_6, 2),
    reach!("crates/axon-services/src/context.rs", "provider-type:VectorStore", TASK_6, 2),
    reach!("crates/axon-services/src/context/target_runtime.rs", "provider-handle:artifact_store", TASK_6, 1),
    reach!("crates/axon-services/src/context/target_runtime.rs", "provider-handle:embedding_provider", TASK_6, 2),
    reach!("crates/axon-services/src/context/target_runtime.rs", "provider-handle:fetch_provider", TASK_6, 1),
    reach!("crates/axon-services/src/context/target_runtime.rs", "provider-handle:render_provider", TASK_6, 1),
    reach!("crates/axon-services/src/context/target_runtime.rs", "provider-handle:vector_store", TASK_6, 2),
    reach!("crates/axon-services/src/context/target_runtime.rs", "provider-type:EmbeddingProvider", TASK_6, 2),
    reach!("crates/axon-services/src/context/target_runtime.rs", "provider-type:VectorStore", TASK_6, 2),
    reach!("crates/axon-services/src/debug.rs", "provider-op:axon_llm::complete_text", TASK_6, 1),
    reach!("crates/axon-services/src/graph.rs", "provider-type:GraphStore", TASK_6, 3),
    reach!("crates/axon-services/src/graph.rs", "provider-method:node_edges", TASK_6, 1),
    reach!("crates/axon-services/src/graph.rs", "provider-method:nodes_for_source", TASK_6, 1),
    reach!("crates/axon-services/src/local_source.rs", "provider-method:ensure_collection", TASK_6, 1),
    reach!("crates/axon-services/src/local_source.rs", "provider-type:EmbeddingProvider", TASK_6, 4),
    reach!("crates/axon-services/src/local_source.rs", "provider-type:VectorStore", TASK_6, 6),
    reach!("crates/axon-services/src/local_source/local_source_job.rs", "provider-type:EmbeddingProvider", TASK_6, 3),
    reach!("crates/axon-services/src/local_source/local_source_job.rs", "provider-type:VectorStore", TASK_6, 3),
    reach!("crates/axon-services/src/local_source/local_source_progress.rs", "provider-handle:vector_store", TASK_6, 1),
    reach!("crates/axon-services/src/local_source/local_source_progress.rs", "provider-type:EmbeddingProvider", TASK_6, 2),
    reach!("crates/axon-services/src/local_source/local_source_progress.rs", "provider-type:VectorStore", TASK_6, 2),
    reach!("crates/axon-services/src/local_source/local_source_publish.rs", "provider-type:VectorStore", TASK_6, 5),
    reach!("crates/axon-services/src/local_source/local_source_publish.rs", "provider-method:mark_generation_committed", TASK_6, 1),
    reach!("crates/axon-services/src/local_source/local_source_publish.rs", "provider-method:mark_unchanged_items_committed", TASK_6, 1),
    reach!("crates/axon-services/src/local_source/local_source_vectorize.rs", "provider-method:embed", TASK_6, 1),
    reach!("crates/axon-services/src/local_source/local_source_vectorize.rs", "provider-type:EmbeddingProvider", TASK_6, 3),
    reach!("crates/axon-services/src/local_source/local_source_vectorize.rs", "provider-type:VectorStore", TASK_6, 3),
    reach!("crates/axon-services/src/memory/import_export.rs", "provider-type:ArtifactStore", TASK_6, 1),
    reach!("crates/axon-services/src/memory/import_export.rs", "provider-method:put_bytes", TASK_6, 1),
    reach!("crates/axon-services/src/memory/store.rs", "provider-handle:embedding_provider", TASK_6, 1),
    reach!("crates/axon-services/src/memory/store.rs", "provider-handle:vector_store", TASK_6, 1),
    reach!("crates/axon-services/src/memory/store.rs", "provider-type:GraphStore", TASK_6, 1),
    reach!("crates/axon-services/src/memory/store.rs", "provider-op:axon_llm::complete_text", TASK_6, 1),
    reach!("crates/axon-services/src/prune.rs", "provider-handle:vector_store", TASK_6, 2),
    reach!("crates/axon-services/src/prune.rs", "provider-type:VectorStore", TASK_6, 2),
    reach!("crates/axon-services/src/query/ask_retrieval.rs", "provider-handle:embedding_provider", TASK_6, 2),
    reach!("crates/axon-services/src/query/ask_retrieval.rs", "provider-handle:vector_store", TASK_6, 2),
    reach!("crates/axon-services/src/query/ask_retrieval.rs", "provider-type:EmbeddingProvider", TASK_6, 2),
    reach!("crates/axon-services/src/query/ask_retrieval.rs", "provider-type:VectorStore", TASK_6, 2),
    reach!("crates/axon-services/src/query/code_search.rs", "provider-handle:embedding_provider", TASK_6, 1),
    reach!("crates/axon-services/src/query/code_search.rs", "provider-handle:vector_store", TASK_6, 1),
    reach!("crates/axon-services/src/query/code_search.rs", "provider-method:embed", TASK_6, 1),
    reach!("crates/axon-services/src/query/code_search_refresh.rs", "provider-handle:embedding_provider", TASK_6, 1),
    reach!("crates/axon-services/src/query/code_search_refresh.rs", "provider-handle:vector_store", TASK_6, 1),
    reach!("crates/axon-services/src/query/retrieval.rs", "provider-handle:embedding_provider", TASK_6, 2),
    reach!("crates/axon-services/src/query/retrieval.rs", "provider-handle:vector_store", TASK_6, 2),
    reach!("crates/axon-services/src/query/retrieval.rs", "provider-type:EmbeddingProvider", TASK_6, 2),
    reach!("crates/axon-services/src/query/retrieval.rs", "provider-type:VectorStore", TASK_6, 2),
    reach!("crates/axon-services/src/query/synthesis/completion.rs", "provider-op:axon_llm::complete_streaming", TASK_6, 1),
    reach!("crates/axon-services/src/query/synthesis/completion.rs", "provider-op:axon_llm::complete_text", TASK_6, 1),
    reach!("crates/axon-services/src/scrape.rs", "provider-type:ArtifactStore", TASK_6, 1),
    reach!("crates/axon-services/src/scrape.rs", "provider-method:put_bytes", TASK_6, 1),
    reach!("crates/axon-services/src/screenshot.rs", "provider-type:ArtifactStore", TASK_6, 1),
    reach!("crates/axon-services/src/screenshot.rs", "provider-method:put_bytes", TASK_6, 1),
    reach!("crates/axon-services/src/search/provider.rs", "provider-type:SearchProvider", TASK_6, 1),
    reach!("crates/axon-services/src/service_traits/provider_service.rs", "provider-handle:vector_store", TASK_6, 1),
    reach!("crates/axon-services/src/source.rs", "provider-handle:artifact_store", TASK_6, 1),
    reach!("crates/axon-services/src/source.rs", "provider-handle:vector_store", TASK_6, 1),
    reach!("crates/axon-services/src/source.rs", "provider-type:GraphStore", TASK_6, 2),
    reach!("crates/axon-services/src/source/dispatch/tool_artifacts.rs", "provider-handle:artifact_store", TASK_6, 1),
    reach!("crates/axon-services/src/source/dispatch/web.rs", "provider-handle:artifact_store", TASK_6, 2),
    reach!("crates/axon-services/src/source/dispatch/web.rs", "provider-handle:embedding_provider", TASK_6, 2),
    reach!("crates/axon-services/src/source/dispatch/web.rs", "provider-handle:fetch_provider", TASK_6, 2),
    reach!("crates/axon-services/src/source/dispatch/web.rs", "provider-handle:render_provider", TASK_6, 2),
    reach!("crates/axon-services/src/source/dispatch/web.rs", "provider-handle:vector_store", TASK_6, 2),
    reach!("crates/axon-services/src/source/graph.rs", "provider-type:GraphStore", TASK_6, 1),
    reach!("crates/axon-services/src/source/graph.rs", "provider-method:upsert_candidates", TASK_6, 1),
    reach!("crates/axon-services/src/source/non_web.rs", "provider-handle:vector_store", TASK_6, 1),
    reach!("crates/axon-services/src/source/non_web/created_generation.rs", "provider-handle:vector_store", TASK_6, 2),
    reach!("crates/axon-services/src/source/non_web/created_generation.rs", "provider-method:ensure_collection", TASK_6, 1),
    reach!("crates/axon-services/src/source/non_web/helpers.rs", "provider-handle:embedding_provider", TASK_6, 1),
    reach!("crates/axon-services/src/source/non_web/helpers.rs", "provider-handle:vector_store", TASK_6, 2),
    reach!("crates/axon-services/src/source/non_web/publish.rs", "provider-type:VectorStore", TASK_6, 2),
    reach!("crates/axon-services/src/source/non_web/publish.rs", "provider-method:mark_generation_committed", TASK_6, 1),
    reach!("crates/axon-services/src/source/non_web/publish.rs", "provider-method:mark_unchanged_items_committed", TASK_6, 1),
    reach!("crates/axon-services/src/source/non_web/vectorize.rs", "provider-handle:embedding_provider", TASK_6, 1),
    reach!("crates/axon-services/src/source/non_web/vectorize.rs", "provider-handle:vector_store", TASK_6, 1),
    reach!("crates/axon-services/src/source/non_web/vectorize.rs", "provider-method:embed", TASK_6, 1),
    reach!("crates/axon-services/src/source/prune.rs", "provider-handle:graph_store", TASK_6, 2),
    reach!("crates/axon-services/src/source/prune.rs", "provider-handle:vector_store", TASK_6, 2),
    reach!("crates/axon-services/src/source/prune.rs", "provider-method:delete_edges", TASK_6, 1),
    reach!("crates/axon-services/src/source/prune.rs", "provider-method:delete_nodes", TASK_6, 1),
    reach!("crates/axon-services/src/source/prune.rs", "provider-type:ArtifactStore", TASK_6, 4),
    reach!("crates/axon-services/src/source/prune.rs", "provider-type:GraphStore", TASK_6, 5),
    reach!("crates/axon-services/src/source/prune.rs", "provider-type:VectorStore", TASK_6, 6),
    reach!("crates/axon-services/src/search/synthesis.rs", "provider-op:axon_llm::complete_streaming", TASK_6, 1),
    reach!("crates/axon-services/src/service_traits/ask_service.rs", "provider-op:axon_llm::complete_text", TASK_6, 1),
    reach!("crates/axon-services/src/summarize.rs", "provider-op:axon_llm::complete_streaming", TASK_6, 1),
    reach!("crates/axon-services/src/endpoints.rs", "provider-type:NetworkCaptureProvider", TASK_6, 3),
    reach!("crates/axon-services/src/uploads.rs", "provider-type:ArtifactStore", TASK_6, 1),
    reach!("crates/axon-services/src/uploads.rs", "provider-method:put_bytes", TASK_6, 1),
    reach!("crates/axon-services/src/uploads/cleanup.rs", "provider-type:ArtifactStore", TASK_6, 1),
    reach!("crates/axon-services/src/web_source.rs", "provider-handle:artifact_store", TASK_6, 4),
    reach!("crates/axon-services/src/web_source.rs", "provider-handle:fetch_provider", TASK_6, 1),
    reach!("crates/axon-services/src/web_source.rs", "provider-handle:render_provider", TASK_6, 1),
    reach!("crates/axon-services/src/web_source.rs", "provider-handle:embedding_provider", TASK_6, 1),
    reach!("crates/axon-services/src/web_source.rs", "provider-handle:vector_store", TASK_6, 1),
    reach!("crates/axon-services/src/web_source.rs", "provider-type:ArtifactStore", TASK_6, 2),
    reach!("crates/axon-services/src/web_source.rs", "provider-type:EmbeddingProvider", TASK_6, 4),
    reach!("crates/axon-services/src/web_source.rs", "provider-type:FetchProvider", TASK_6, 2),
    reach!("crates/axon-services/src/web_source.rs", "provider-type:RenderProvider", TASK_6, 2),
    reach!("crates/axon-services/src/web_source.rs", "provider-type:VectorStore", TASK_6, 4),
    reach!("crates/axon-services/src/web_source/artifacts.rs", "provider-handle:artifact_store", TASK_6, 2),
    reach!("crates/axon-services/src/web_source/artifacts.rs", "provider-method:put_bytes", TASK_6, 1),
    reach!("crates/axon-services/src/web_source/artifacts.rs", "provider-type:ArtifactStore", TASK_6, 4),
    reach!("crates/axon-services/src/web_source/normalize.rs", "provider-handle:fetch_provider", TASK_6, 2),
    reach!("crates/axon-services/src/web_source/normalize.rs", "provider-handle:render_provider", TASK_6, 2),
    reach!("crates/axon-services/src/web_source/publish.rs", "provider-type:VectorStore", TASK_6, 6),
    reach!("crates/axon-services/src/web_source/publish.rs", "provider-method:mark_generation_committed", TASK_6, 1),
    reach!("crates/axon-services/src/web_source/publish.rs", "provider-method:mark_unchanged_items_committed", TASK_6, 1),
    reach!("crates/axon-services/src/web_source/vector_publish.rs", "provider-handle:artifact_store", TASK_6, 7),
    reach!("crates/axon-services/src/web_source/vector_publish.rs", "provider-handle:embedding_provider", TASK_6, 3),
    reach!("crates/axon-services/src/web_source/vector_publish.rs", "provider-handle:vector_store", TASK_6, 9),
    reach!("crates/axon-services/src/web_source/vector_publish.rs", "provider-method:ensure_collection", TASK_6, 1),
    reach!("crates/axon-services/src/web_source/vector_publish.rs", "provider-type:ArtifactStore", TASK_6, 1),
    reach!("crates/axon-services/src/web_source/vector_publish.rs", "provider-type:EmbeddingProvider", TASK_6, 3),
    reach!("crates/axon-services/src/web_source/vector_publish.rs", "provider-type:VectorStore", TASK_6, 6),
    reach!("crates/axon-services/src/web_source/vectorize.rs", "provider-handle:artifact_store", TASK_6, 4),
    reach!("crates/axon-services/src/web_source/vectorize.rs", "provider-method:embed", TASK_6, 1),
    reach!("crates/axon-services/src/web_source/vectorize.rs", "provider-type:EmbeddingProvider", TASK_6, 3),
    reach!("crates/axon-services/src/web_source/vectorize.rs", "provider-type:VectorStore", TASK_6, 3),
    reach!("crates/axon-services/src/web_source/web_source_job.rs", "provider-type:EmbeddingProvider", TASK_6, 3),
    reach!("crates/axon-services/src/web_source/web_source_job.rs", "provider-type:VectorStore", TASK_6, 3),
];
